version: '3'

services:

  commands:
    build: ./commands
    container_name: commands
    expose:
      - "50051"
    environment:
      - "CONSUL_HTTP_ADDR=consul:8500"

  web:
    build: ./web
    container_name: web
    expose:
      - "8080"
    ports:
      - "80:8080"
    environment:
      - "CONSUL_HTTP_ADDR=consul:8500"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shortyio
    volumes:
      - ./common/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
