version: '3'

services:

  flipflop:
    build: ./Commands/FlipFlop
    expose:
      - "50051"

  web:
    build: ./Web
    expose:
      - "8080"
    ports:
      - "80:8080"
    environment:
      - SERVER_ADDRESS=flipflop:50051

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shortyio
    volumes:
      - ./Shared/db/schemas/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
