version: '3'

services:
  consulserver:
    command: "agent -server -ui -bootstrap-expect=1 -client=0.0.0.0"
    container_name: consul
    expose:
      - "8600"
      - "8500"
    image: consul:latest
    networks:
      - consul-network
    ports:
      - "8500:8500"
      - "8600:8600/udp"

  # keycloak:
  #   command: "start-dev"
  #   container_name: keycloak
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #   image: quay.io/keycloak/keycloak:latest
  #   ports:
  #     - "2020:8080"
  #   restart: always

  # flipflop:
  #   build:
  #     args:
  #       - DIR=Commands/FlipFlop/
  #     context: .
  #     dockerfile: ./Commands/FlipFlop/dockerfile
  #   depends_on:
  #     - consul
  #   environment:
  #     - CONSUL_HTTP_ADDR=consul:8500
  #   expose:
  #     - "50051"
  #     - "8500"
  #   networks:
  #     - consul-network
  #   restart: always

  # db:
  #   environment:
  #   image: postgres:13-alpine
  #   ports:
  #    - "5432:5432"
  #   volumes:
  #     - ./Shared/db/schemas/schema.sql:/docker-entrypoint-initdb.d/init.sql

  # query:
  #   build:
  #     args:
  #       - DIR=Queries/Block
  #     context: .
  #     dockerfile: ./Queries/Block/Dockerfile
  #   depends_on:
  #     - consulserver
  #   environment:
  #     - CONSUL_HTTP_ADDR=consulserver:8500
  #   expose:
  #     - "50051"
  #     - "8500"
  #   networks:
  #     - consul-network
  #   restart: always

  nats:
    image: nats
    expose:
      - "4222"


  aggregator:
    build:
      args:
        - DIR=Aggregator
      context: .
      dockerfile: ./Aggregator/Dockerfile
    depends_on:
      - consulserver
    environment:
      - CONSUL_HTTP_ADDR=consulserver:8500
    expose:
      - "50051"
    networks:
      - consul-network
    restart: always

  web:
    build:
      args:
        - DIR=Web
      context: .
      dockerfile: ./Web/Dockerfile
    depends_on:
      - consulserver
      - keycloak
    environment:
      - CONSUL_HTTP_ADDR=consulserver:8500
    expose:
      - "50051"
      - "8500"
    networks:
      - consul-network
    ports:
      - "42069:8080"
    restart: always

networks:
  consul-network:
    driver: bridge
