version: '3'

services:

  consul:
    command: "agent -server -ui -bootstrap-expect=1 -client=0.0.0.0"
    container_name: consul
    expose:
      - "8600"
      - "8500"
    image: consul:latest
    networks:
      - consul-network
    ports:
      - "8500:8500"
      - "8600:8600/udp"

  keycloak:
    container_name: keycloak
    command: "start-dev"
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "2020:8080"
    restart: always

  query:
    build:
      args:
        - DIR=Queries/Block
      context: .
      dockerfile: ./Queries/Block/Dockerfile
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    expose:
      - "50051"
      - "8500"
    networks:
      - consul-network
    restart: always

  # flipflop:
  #   build:
  #     args:
  #       - DIR=Commands/FlipFlop/
  #     context: .
  #     dockerfile: ./Commands/FlipFlop/dockerfile
  #   depends_on:
  #     - consul
  #   environment:
  #     - CONSUL_HTTP_ADDR=consul:8500
  #   expose:
  #     - "50051"
  #     - "8500"
  #   networks:
  #     - consul-network
  #   restart: always

  web:
    build:
      args:
        - DIR=Web
      context: .
      dockerfile: ./Web/Dockerfile
    depends_on:
      - consul
      - keycloak
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - "target=consul://consul:8500/Queries"
      - QUERIES=query:50051
      # - FLIPFLOP=flipflop
    expose:
      - "50051"
      - "8500"
    networks:
      - consul-network
    ports:
      - "42069:8080"
    restart: always

  # db:
  #   image: postgres:13-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: shortyio
  #   volumes:
  #     - ./Shared/db/schemas/schema.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "5432:5432"

networks:
  consul-network:
    driver: bridge
