version: '3'

services:
  consulserver:
    command: "agent -server -ui -bootstrap-expect=1 -client=0.0.0.0"
    container_name: consul
    expose:
      - "8600"
      - "8500"
    image: consul:latest
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./kv.json:/kv.json

  # keycloak:
  #   command: "start-dev"
  #   container_name: keycloak
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #   image: quay.io/keycloak/keycloak:21.1.1
  #   ports:
  #     - "2020:8080"
  #   restart: always

  flipflop:
    build:
      args:
        - DIR=Commands/FlipFlop
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - consulserver
    environment:
      - CONSUL_HTTP_ADDR=consulserver:8500
      - NATS=nats:4222
    expose:
      - "50051"
      - "8500"
    restart: always

  db:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:13-alpine
    ports:
     - "5432:5432"
    volumes:
      - ./Shared/db/schemas/schema.sql:/docker-entrypoint-initdb.d/init.sql

  query:
    build:
      args:
        - DIR=Queries/Block
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - consulserver
    environment:
      - CONSUL_HTTP_ADDR=consulserver:8500
    deploy:
      mode: replicated
      replicas: 3
    expose:
      - "50051"
      - "8500"
    restart: always

  nats:
    expose:
      - "4222"
    image: nats

  # aggregator:
  #   build:
  #     args:
  #       - DIR=Aggregator
  #     context: .
  #     dockerfile: ./Web/Dockerfile
  #   depends_on:
  #     - consulserver
  #   environment:
  #     - CONSUL_HTTP_ADDR=localhost:8500
  #     - NATS=nats:4222
  #   expose:
  #     - "50051"
  #   restart: always

  web:
    build:
      args:
        - DIR=Web
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - consulserver
      # - keycloak
    environment:
      - CONSUL_HTTP_ADDR=consulserver:8500
      - NATS=nats:4222
    expose:
      - "50051"
      - "8500"
    ports:
      - "42069:8080"
    restart: always
